### ISSUE TITLE
You can't implement ordinary json requests instead of react native fetch.

### ISSUE THREAD

**Issue by skyliwq** [edeckers/react-native-blob-courier#124] opened 2021-02-03 07:37 UTC
**Is your feature request related to a problem? Please describe.**
You can't implement ordinary json requests instead of react native fetch.

**Describe the solution you'd like**
Refer to：https://github.com/r0b0t3d/react-native-netify

**Comment by edeckers** [comment] 2021-02-04 18:17
Hey @skyliwq , thank you for reaching out! I'm not sure I fully understand your question though, because I _think_ this functionality is already present or there has been a regression. So before I make any assumptions let's make sure we're on the same page.

Am I correct when you want to be able to send a json object with upload requests, instead of either a file path or a plain text string? Is this the functionality you're looking for? https://github.com/edeckers/react-native-blob-courier/blob/46eb21e67a0b495a6a41b743e8a5e6b8f1d404b5/src/__tests__/index.test.tsx#L700

**Comment by skyliwq** [comment] 2021-02-05 13:35
I mean is it possible to do network request instead of fetch

fetch('https://api.github.com/users/chriscoyier/repos')
  .then(response => response.json())
  .then(data => {
    console.log(data)
  });

**Comment by edeckers** [comment] 2021-02-05 14:05
It is not a feature at the moment, because I figured people can use `react-native-blob-courier` for downloading and uploading large files or blobs, and simply use `fetch` for the rest of their requests.

Is there a particular reason why that does not work for you, or why adding a `fetch` functionality to `react-native-blob-courier` would make your life easier?

**Comment by edeckers** [comment] 2021-02-09 09:06
Since there hasn't been any follow up I consider this issue to be resolved with the approach suggested in my last comment. If it isn't, please open a new issue.

**Closed** 2021-02-09 09:07 UTC
Labels: question, wontfix
